#!/usr/bin/env bash
# Rewrite the auth stack of /etc/pam.d/sshd to require a TOTP code, while
# leaving exempt accounts on their original authenticator.
#
# Only /etc/pam.d/sshd is touched. system-auth and password-auth are managed
# by authselect and must never be hand-edited: authselect would revert them,
# and a mistake there breaks sudo, login and cron as well as sshd.
#
# The block itself is generated by pam_block() in lib/common.sh, which
# tests/test-pam-stack.sh covers.
#
# Usage: 20-configure-pam.sh [--dry-run]

. "$(dirname "$(readlink -f "$0")")/lib/common.sh"
require_root
load_config

DRY=no
[[ "${1:-}" == "--dry-run" ]] && DRY=yes

PAMF=/etc/pam.d/sshd
MOD="$(pam_module_path)" \
  || die "pam_google_authenticator.so not found; run 10-install-packages.sh first"
[[ -f "$PAMF" ]] || die "$PAMF missing"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

grep -qE "$PAM_ANCHOR" "$PAMF" || die \
  "no 'auth substack password-auth' line in $PAMF. The file has been customised; apply the block from docs/MANUAL-STEPS.md by hand."

# pam_render replaces any prior managed block, so this is safe to re-run.
pam_render < "$PAMF" > "$tmp" \
  || die "failed to insert the MFA block into $PAMF"

if [[ "$DRY" == "yes" ]]; then
  log "--dry-run: proposed changes to $PAMF"
  diff -u "$PAMF" "$tmp" || true
  exit 0
fi

backup_file "$PAMF"
install -m 0644 -o root -g root "$tmp" "$PAMF"
command -v restorecon >/dev/null && restorecon -F "$PAMF" 2>/dev/null || true
ok "wrote $PAMF (mode=$AUTH_MODE nullok=$NULLOK)"
ok "module present: $MOD"

echo
log "resulting auth stack:"
grep -nE '^[[:space:]]*auth' "$PAMF" | sed 's/^/    /'
echo
warn "sshd is NOT reloaded by this script. Run 30-configure-sshd.sh next."
